const CONFIG = {
    introTitle: 'Hi',
    introDesc: `I just wanna tell you`,
    btnIntro: '<3',
    title: 'Em hỏi chị cái này nhé 😙',
    desc: 'chị có yêu em không? (trả lời thật tâm nhé)',
    btnYes: 'có',
    btnNo: 'không',
    question:'sao lại yêu em',
    btnReply: '^ ^',
    Reply: '',
    mess: '',
    messDesc: 'hỏi thế thôi chứ em biết em đáng yêu vô điều kiện mà:))',
    btnAccept:  '<3',
}
