const CONFIG = {
    introTitle: 'Hi',
    introDesc: `I just wanna tell you`,
    btnIntro: '<3',
    title: 'Nhân dịp 20/10 mình chúc các bạn nữ sớm có ny nha 😙',
    desc: 'còn ai có rồi thì thôi :)) ',
    btnYes: 'mấy bạn nhận lời chúc của mình nhé?',
    btnNo: 'hog nhận thì thoi :3',
    question:'Happy women day',
    btnReply: '^ ^',
    Reply: '',
    mess: '',
    messDesc: 'hết r còn gì nữa đâu mà coi :))',
    btnAccept:  '<3',
}
